name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

        if: ${{ github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '#skip') }}
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{secrets.RENDER_SERVICE_ID}}?key=${{secrets.RENDER_API_KEY}}

      - name: Build failed
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          text: Build failed
          description: Error.
          details: commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username }} broke the build :(
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    if: ${{ github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: A new version of Pokedex deployed and tagged
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          text: A new version of Pokedex deployed
          description: Success!
          details: "to https://p11-fs-open-pokedex.fly.dev/ by SamuYliK"
          footer: "Severity: Informational"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
